name: Build binaries in each platform
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        builds:
          - name: macos-x86_64
            os: macos-latest
            ocaml_version: 4.12.1
            opam_dir: "/Users/runner/work/satyst-dist/satyst-dist/_opam"
          - name: linux-x86_64
            os: ubuntu-latest
            ocaml_version: 4.12.1
            opam_dir: "/home/runner/work/satyst-dist/satyst-dist/_opam"
          - name: windows-x86_64
            os: windows-latest
            ocaml_version: 4.12.1
            opam_dir: "D:\\a\\satyst-dist\\satyst-dist\\_opam"

    runs-on: ${{ matrix.builds.os }}

    steps:
      - name: Extract GITHUB_BRANCH
        shell: bash
        run: echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      - name: Add msbuild to PATH (windows)
        uses: microsoft/setup-msbuild@v1.1
        if: contains(matrix.builds.os, 'windows')

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache OPAM files
        uses: actions/cache@v2
        with:
          key: opam-${{ matrix.builds.os }}-${{ matrix.builds.ocaml_version }}-${{ matrix.builds.opam_dir }}
          path: ${{ matrix.builds.opam_dir }}

      - name: Use OCaml ${{ matrix.builds.ocaml_version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.builds.ocaml_version }}

      - name: Extract OPAM_SWITCH_PREFIX (windows)
        run: "opam env | Select-String -Pattern \"OPAM_SWITCH_PREFIX\" | %{ \"OPAM_SWITCH_PREFIX=\" + $_.Line.split(\"'\")[1] } | Add-Content -Path \"$env:GITHUB_ENV\""
        if: contains(matrix.builds.os, 'windows')
          
      - name: Extract OPAM_SWITCH_PREFIX (not windows)
        run: "eval $(opam env); echo \"OPAM_SWITCH_PREFIX=$OPAM_SWITCH_PREFIX\" >> \"$GITHUB_ENV\""
        if: ${{!(contains(matrix.builds.os, 'windows'))}}

      - name: dump vars
        shell: bash
        run: |
          echo "OPAM_SWITCH_PREFIX=$OPAM_SWITCH_PREFIX"
          echo "GITHUB_BRANCH=$GITHUB_BRANCH"

      - name: Add opam repos
        run: |
          opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
          opam repository add satyrographos-repo https://github.com/na4zagin3/satyrographos-repo.git

      - name: Install SATySFi packages for version ${{ env.GITHUB_BRANCH }}
        run: |
          opam install satysfi.${{ env.GITHUB_BRANCH }} -y
          opam install satysfi-dist.${{ env.GITHUB_BRANCH  }} -y
        env:
          OPAMUNLOCKBASE: true

      - name: Copy files (not windows)
        run: |
          mkdir -p ./bin ./share
          cp -rf "$OPAM_SWITCH_PREFIX/bin/satysfi" ./bin/
          cp -rf "$OPAM_SWITCH_PREFIX/share/satysfi" ./share/
        if: ${{!(contains(matrix.builds.os, 'windows'))}}

      - name: Copy files (windows)
        run: |
          New-Item -ItemType "directory" -Path ".\\bin" -Force
          New-Item -ItemType "directory" -Path ".\\share" -Force
          Copy-Item -Path ($env:OPAM_SWITCH_PREFIX + "\\bin\\satysfi.exe")  -Destination ".\\bin"
          Copy-Item -Path ($env:OPAM_SWITCH_PREFIX + "\\share\\satysfi")  -Destination ".\\share"
        if: contains(matrix.builds.os, 'windows')

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build satysfi-language-server
        working-directory: ./satysfi-language-server
        run: cargo build --release

      - name: copy satysfi-language-server (windows)
        run: Copy-Item ".\\satysfi-language-server\\target\\release\\satysfi-language-server.exe" -Destination ".\\bin"
        if: contains(matrix.builds.os, 'windows')

      - name: copy satysfi-language-server (not windows)
        run: cp -rf "./satysfi-language-server/target/release/satysfi-language-server" ./bin/
        if: ${{!(contains(matrix.builds.os, 'windows'))}}

      - name: git setting
        run: |
          git config --local user.email "yasuo@ozu.email"
          git config --local user.name "yasuo-ozu"

      - name: Commit files
        run: |
          git reset
          git add bin share
          git commit -m "Update bin and share"
          git tag -f ${{matrix.builds.name}}/${{ env.GITHUB_BRANCH  }}
          git push origin ${{matrix.builds.name}}/${{ env.GITHUB_BRANCH }}
          git reset --hard 'HEAD^'

